language: ruby
sudo: false
before_install:
  - gem install bundler
script:
  - "bundle exec $CHECK"
notifications:
  email: false
rvm:
  - 2.4.1
  - 2.3.3

env:
  - "CHECK='rspec spec'"
  - "CHECK=rubocop"
